import {createActions} from "reduxsauce";

const { Types, Creators} = createActions({
    getAllMerchantsByCategory: ["data"],
    getAllMerchantsByCategorySuccess: ["data"],
    getAllMerchantsByCategoryFailure: ["error"],
    getMerchantsByBrand: ["data"],
    getMerchantsByBrandSuccess: ["data"],
    getMerchantsByBrandFailure: ["error"],
    getMerchant: ["data"],
    getMerchantSuccess: ["data"],
    getMerchantFailure: ["error"],
    setSelectedMerchantId: ['data'],
    setSelectedMerchantIdSuccess: ['data'],
    setSelectedMerchantIdFailure: ['error'],
    updateMerchant: ["data"],
    updateMerchantSuccess: ["data"],
    updateMerchantFailure: ["error"],
    getPendingMerchantsList: ["data"],
    getPendingMerchantsListSuccess: ["data"],
    getPendingMerchantsListFailure: ["error"],
    getAllMerchants: ["data"],
    getAllMerchantsSuccess: ["data"],
    getAllMerchantsFailure: ["error"],
    handleMerchantApproval: ["data"],
    handleMerchantApprovalSuccess: ["data"],
    handleMerchantApprovalFailure: ["error"],
    getMerchantSummery: ["data"],
    getMerchantSummerySuccess: ["data"],
    getMerchantSummeryFailure: ["error"],
    searchMerchantsForBrand: ["data"],
    searchMerchantsForBrandSuccess: ["data"],
    searchMerchantsForBrandFailure: ["error"],
    searchMerchantsForCategory: ["data"],
    searchMerchantsForCategorySuccess: ["data"],
    searchMerchantsForCategoryFailure: ["error"],
    handleMerchantBlocking: ["data"],
    handleMerchantBlockingSuccess: ["data"],
    handleMerchantBlockingFailure: ["error"],    
    ApproveMerchant:["data"],
    ApproveMerchantSuccess:["data"],
    ApproveMerchantFailure:["error"],
    getPendingBusinessInfoList:["data"],
    getPendingBusinessInfoListSuccess:["data"],
    getPendingBusinessInfoListFailure:["error"],
    getPendingContactInfoList:["data"],
    getPendingContactInfoListSuccess:["data"],
    getPendingContactInfoListFailure:["error"],
    approvePendingMerchent:["data"],
    approvePendingMerchentSuccess:["data"],
    approvePendingMerchentFailure:["error"],
    approvePendingBusinessInfo:["data"],
    approvePendingBusinessInfoSuccess:["data"],
    approvePendingBusinessInfoFailure:["error"],
    approvePendingContactInfo:["data"],
    approvePendingContactInfoSuccess:["data"],
    approvePendingContactInfoFailure:["error"],
    getPendingBusinessDetails:["data"],
    getPendingBusinessDetailsSuccess:["data"],
    getPendingBusinessDetailsFailure:["error"],
    getPendingContactDetails:["data"],
    getPendingContactDetailsSuccess:["data"],
    getPendingContactDetailsFailure:["error"],
    updateMerchantBusinessInfo: ["data"],
    updateMerchantBusinessInfoSuccess: ["data"],
    updateMerchantBusinessInfoFailure: ["error"],
    updateMerchantBasicInfo: ["data"],
    updateMerchantBasicInfoSuccess: ["data"],
    updateMerchantBasicInfoFailure: ["error"],
    updateMerchantContactInfo: ["data"],
    updateMerchantContactInfoSuccess: ["data"],
    updateMerchantContactInfoFailure: ["error"],
    getContactInfoByMerchantId: ["data"],
    getContactInfoByMerchantIdSuccess: ["data"],
    getContactInfoByMerchantIdFailure: ["error"],
    getBusinessInfoByMerchantId: ["data"],
    getBusinessInfoByMerchantIdSuccess: ["data"],
    getBusinessInfoByMerchantIdFailure: ["error"],
    updateCategoriesAndBrandsForMerchant: ["data"],
    updateCategoriesAndBrandsForMerchantSuccess: ["data"],
    updateCategoriesAndBrandsForMerchantFailure: ["error"],
    getBrandsCategoriesMappingByMerchant: ["data"],
    getBrandsCategoriesMappingByMerchantSuccess: ["data"],
    getBrandsCategoriesMappingByMerchantFailure: ["error"],
    updateMerchantEmail: ["data"],
    updateMerchantEmailSuccess: ["data"],
    updateMerchantEmailFailure: ["error"],
    updateMerchantMobileNo: ["data"],
    updateMerchantMobileNoSuccess: ["data"],
    updateMerchantMobileNoFailure: ["error"],
    resetMerchantState: [],
    resetMerchantStateSuccess: []
})
export const MERCHANTS = Types;
export default Creators;