import { createActions } from "reduxsauce";

//javascrip actions as object

const { Types, Creators } = createActions({
  createDeal: ["data"],
  createDealSuccess: ["data"],
  createDealFailure: ["error"],
  searchOnAllDeals: ["data"],
  searchOnAllDealsSuccess: ["data"],
  searchOnAllDealsFailure: ["error"],
  getAllDealsByMerchant: ["data"],
  getAllDealsByMerchantSuccess: ["data"],
  getAllDealsByMerchantFailure: ["error"],
  getDeal: ["data"],
  getDealSuccess: ["data"],
  getDealFailure: ["error"],
  setSelectedDealId: ["data"],
  setSelectedDealIdSuccess: ["data"],
  setSelectedDealIdFailure: ["error"],
  handleDealApproval: ["data"],
  handleDealApprovalSuccess: ["data"],
  handleDealApprovalFailure: ["error"],
  deleteDeal: ["data"],
  deleteDealSuccess: ["data"],
  deleteDealFailure: ["error"],  
  searchDealsForCategory: ["data"],
  searchDealsForCategorySuccess: ["data"],
  searchDealsForCategoryFailure: ["error"],
  searchDealsForBrand: ["data"],
  searchDealsForBrandSuccess: ["data"],
  searchDealsForBrandFailure: ["error"],
  getPendingDealsList:["data"],
  getPendingDealsListSuccess:["data"],
  getPendingDealsListFailure:["error"], 
  approvePendingDeal:["data"],
  approvePendingDealSuccess :["data"],
  approvePendingDealFailure :["error"],
  getDealByID: ["data"],
  getDealByIDSuccess: ["data"],
  getDealByIDFailure: ["error"],
  createOfferType:["data"],
  createOfferTypeSuccess :["data"],
  createOfferTypeFailure :["error"],
  getAllOfferTypes:["data"],
  getAllOfferTypesSuccess :["data"],
  getAllOfferTypesFailure :["error"],
  getCombinedDealRequestsList:["data"],
  getCombinedDealRequestsListSuccess :["data"],
  getCombinedDealRequestsListFailure :["error"],
  getDealRequestsListForCombination: ["data"],
  getDealRequestsListForCombinationSuccess: ["data"],
  getDealRequestsListForCombinationFailure: ["error"],
  getSummeryForDealRequestsListForCombination: ["data"],
  getSummeryForDealRequestsListForCombinationSuccess: ["data"],
  getSummeryForDealRequestsListForCombinationFailure: ["error"],
  resetDealsState: [],
  resetDealsStateSuccess: [],
  getAudienceReachSummeryReportForDeals: ["data"],
  getAudienceReachSummeryReportForDealsSuccess: ["data"],
  getAudienceReachSummeryReportForDealsFailure: ["error"],
});

export const DEALS = Types;
export default Creators;


