name: sonar

on:
  push:
    branches:
      - main
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: https://sonarqube.qpon.lk
        login: 335df1130852aabd9095b2a841f6206076904f1d
        projectKey: "web-app"
        projectName: "web-app"
