name: sonar

on:
  push:
    branches:
      - main
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      run: sonar-scanner
           -Dsonar.organization=web-app 
           -Dsonar.projectKey=web-app
           -Dsonar.sources=$GITHUB_WORKSPACE 
           -Dsonar.host.url=https://sonarqube.qpon.lk
           -Dsonar.login=335df1130852aabd9095b2a841f6206076904f1d
