name: s3-deployment-development

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: 	ubuntu-latest
    env: 
      CI: false
    steps:
      - uses: actions/checkout@v2
      - name: Build React App
        run: |
          npm install -g npm-check-updates
          ncu -u
          npm install postcss -g
          npm i caniuse-lite browserslist
          yarn
          yarn build:qa
          npx browserslist@latest --update-db
          ls -lha
      - name: Deploy qpon app build to S3 bucket and invalidate cloudfront cache
        run: |
           aws s3 sync ./build/ s3://frontend-qpon-dev --delete
           aws cloudfront create-invalidation --distribution-id E3LNRIA8MLCDT3 --paths "/*"

