name: s3-deployment-development

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI: false
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS CredentialsUpdate
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: |
          npm install postcss -g
          yarn
          yarn build:dev
          ls -lha
      - name: Deploy qpon app build to S3 bucket and invalidate cloudfront cache
        run: |
           aws s3 sync ./build/ s3://frontend-qpon-dev --delete
           aws cloudfront create-invalidation --distribution-id E3LNRIA8MLCDT3 --paths "/*"
